name: Scheduled ingatlan
on:
  schedule:
  - cron: 0 3 * * *
jobs:
  cron-run-ingatlan:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: Scheduled ingatlan
      env:
        ZIMMER_AUTH_HEX: ${{ secrets.ZIMMER_AUTH_HEX }}
        ZIMMER_PHRASE: ${{ secrets.ZIMMER_PHRASE }}
        GIT_HTTPS_TOKEN: ${{ secrets.GIT_HTTPS_TOKEN }}
        ASWAN_AUTH_PASS: ${{ secrets.ASWAN_AUTH_PASS }}
        ASWAN_AUTH_HEX: ${{ secrets.ASWAN_AUTH_HEX }}
        ASWAN_REMOTE: ${{ secrets.ASWAN_REMOTE }}
      run: ./webext-runner.sh
